<<<<<<< Updated upstream
=======
[20-Jul-2023 14:25:52 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 14:30:51 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 14:35:52 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 14:40:51 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 14:45:51 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 14:50:51 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 14:55:51 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 14:58:38 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:58:39 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:58:48 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:58:48 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:58:55 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:58:56 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:58:56 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:58:57 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:58:57 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:58:59 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:00 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:02 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:04 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:04 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:04 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:04 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:05 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:05 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:08 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:08 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:16 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:19 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:20 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:20 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:22 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:23 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:26 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:30 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:31 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:31 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:31 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:32 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:32 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:34 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:34 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:35 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:35 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:36 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:37 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:37 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:39 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:39 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:41 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:42 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:42 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:44 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:44 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:44 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:45 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:45 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:46 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 14:59:47 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:05 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:06 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:06 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:07 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:08 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:08 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:08 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:09 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:09 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:10 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:10 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:11 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:11 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:12 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:12 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:28 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:28 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:29 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.80.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[20-Jul-2023 15:00:51 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 15:05:51 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 15:10:51 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 15:15:51 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 15:20:51 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 20:26:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 20:31:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 20:36:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 20:41:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 20:46:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 20:51:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 20:56:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 21:01:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 21:06:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 21:11:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 21:16:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 21:21:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 21:26:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 21:31:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 21:36:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 21:41:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 21:46:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 21:51:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 21:56:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 22:01:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 22:06:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 22:11:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 22:16:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 22:21:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 22:26:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 22:31:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 22:36:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 22:41:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 22:46:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 22:51:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 22:56:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[20-Jul-2023 23:01:15 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[20-Jul-2023 23:29:07 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[20-Jul-2023 23:34:07 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[20-Jul-2023 23:39:08 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[20-Jul-2023 23:49:05 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 00:19:26 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 00:24:26 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 00:29:26 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 00:50:29 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 01:29:05 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 01:34:05 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 01:39:05 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 02:15:55 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 02:20:55 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 02:25:55 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 02:47:36 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 03:24:24 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 03:29:24 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 03:34:24 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 04:26:54 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 04:31:54 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 04:36:54 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 04:57:23 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 05:18:57 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 05:23:57 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 05:28:57 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 06:00:39 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 06:21:26 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 06:26:26 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 06:31:26 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 07:09:30 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 07:14:31 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 07:19:31 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 07:45:09 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 08:05:36 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 08:10:36 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 08:15:36 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 08:37:21 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 08:57:18 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 09:02:18 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 09:07:18 America/Los_Angeles] PDOException: SQLSTATE[HY000] [2002] No such file or directory in /Users/josephroberts/localdev/leantime/app/core/class.db.php:74
Stack trace:
#0 /Users/josephroberts/localdev/leantime/app/core/class.db.php(74): PDO->__construct('mysql:host=loca...', 'root', 'root', Array)
#1 /Users/josephroberts/localdev/leantime/app/core/class.db.php(99): leantime\core\db->__construct()
#2 /Users/josephroberts/localdev/leantime/app/domain/setting/repositories/class.setting.php(25): leantime\core\db::getInstance()
#3 /Users/josephroberts/localdev/leantime/app/core/class.language.php(76): leantime\domain\repositories\setting->__construct()
#4 /Users/josephroberts/localdev/leantime/app/core/class.language.php(162): leantime\core\language->__construct()
#5 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(142): leantime\core\language::getInstance()
#6 /Users/josephroberts/localdev/leantime/app/domain/auth/services/class.auth.php(154): leantime\domain\services\auth->__construct('960961cb376861c...')
#7 /Users/josephroberts/localdev/leantime/app/core/class.application.php(46): leantime\domain\services\auth::getInstance('960961cb376861c...')
#8 /Users/josephroberts/localdev/leantime/public/index.php(24): leantime\core\application->__construct(Object(leantime\core\IncomingRequest))
#9 {main}
[21-Jul-2023 09:17:39 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[21-Jul-2023 09:22:39 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[21-Jul-2023 09:27:39 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[21-Jul-2023 09:32:39 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
>>>>>>> Stashed changes
[21-Jul-2023 09:37:39 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[21-Jul-2023 09:42:17 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:18 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:26 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:27 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:35 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:35 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:35 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:36 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:36 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:39 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:39 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:42 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:44 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:44 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:45 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:45 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:46 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:46 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:48 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:48 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:48 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:42:56 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:00 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:01 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:01 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:02 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:02 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:03 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:06 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:10 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:11 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:12 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:12 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:13 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:13 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:13 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:15 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:16 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:16 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:16 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:18 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:18 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:19 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:19 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:21 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:22 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:27 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:27 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:28 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:30 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:30 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:31 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:32 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:32 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:32 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:32 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:35 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:55 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:56 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:56 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:57 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:58 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:58 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:43:58 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:44:01 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:44:01 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:44:01 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:44:01 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:44:02 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:44:02 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:44:03 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:44:03 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:44:03 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:44:06 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:44:06 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:44:23 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:44:24 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 09:44:24 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: 192.168.128.1:9003 (from REMOTE_ADDR HTTP header), host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port).
[21-Jul-2023 11:40:38 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
[21-Jul-2023 11:45:41 America/Los_Angeles] Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9000 (through xdebug.client_host/xdebug.client_port) :-(
